// OpenCL stub for NDK build
// Provides all symbols referenced by ggml-opencl at link time.
// At runtime, the device's libOpenCL.so is used.
#include <stddef.h>
#define STUB(name) extern "C" void name() {}

STUB(clBuildProgram)
STUB(clCreateBuffer)
STUB(clCreateBufferWithProperties)
STUB(clCreateCommandQueue)
STUB(clCreateContext)
STUB(clCreateImage)
STUB(clCreateKernel)
STUB(clCreateProgramWithSource)
STUB(clCreateSubBuffer)
STUB(clEnqueueBarrierWithWaitList)
STUB(clEnqueueCopyBuffer)
STUB(clEnqueueFillBuffer)
STUB(clEnqueueMarkerWithWaitList)
STUB(clEnqueueNDRangeKernel)
STUB(clEnqueueReadBuffer)
STUB(clEnqueueWriteBuffer)
STUB(clFinish)
STUB(clFlush)
STUB(clGetDeviceIDs)
STUB(clGetDeviceInfo)
STUB(clGetEventProfilingInfo)
STUB(clGetKernelInfo)
STUB(clGetKernelSubGroupInfo)
STUB(clGetKernelWorkGroupInfo)
STUB(clGetPlatformIDs)
STUB(clGetPlatformInfo)
STUB(clGetProgramBuildInfo)
STUB(clReleaseCommandQueue)
STUB(clReleaseContext)
STUB(clReleaseEvent)
STUB(clReleaseKernel)
STUB(clReleaseMemObject)
STUB(clReleaseProgram)
STUB(clRetainContext)
STUB(clSetKernelArg)
STUB(clWaitForEvents)
